### ISSUE TITLE
Unbounded Query when retrieving the revocation list

### ISSUE THREAD

**Issue by enzian** [admin-ch/CovidCertificate-Management-Service#3]
The implementation of `findAllUvcis` has an unbounded query. This is not an issue for 1000s of revocations, but considering that entire lots of certain vaccines could become known as ineffective, the number of revoked certificates may quickly increase by 10^5 certificates weekly. Devices calling this endpoint even in small numbers on a daily basis will potentially DoS the system, exceed any limits for response body sizes and provoke timeouts.

```Java
@Repository
public interface RevocationRepository extends JpaRepository<Revocation, UUID> {
    Revocation findByUvci(String uvci);

    @Query("SELECT r.uvci FROM Revocation r")
    List<String> findAllUvcis();
}
```

**Comment by delixfe** [comment]
@enzian: Thanks for your input. The endpoint is not directly accessible. The data is only available via the Verification API and through heavy caching. 
We will need to optimize the endpoint in the management-service in the near future.
